begin;

create table if not exists public.users (
  id bigint primary key generated by default as identity,
  email text not null,
  password_hash text,
  solana_wallet_address text,
  auth_user_id uuid,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.listings (
  id bigint primary key generated by default as identity,
  title text,
  description text,
  price_fiat numeric(18, 2),
  price_crypto numeric(38, 9),
  city text,
  rooms integer,
  lat double precision,
  lng double precision,
  area numeric(18, 2),
  floor integer,
  images text[] not null default '{}'::text[],
  seller_wallet_address text,
  token_mint_address text,
  tokenization_status text default 'draft',
  tokenization_error text,
  owner_id bigint references public.users (id) on update cascade on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id bigint primary key generated by default as identity,
  listing_id bigint references public.listings (id) on update cascade on delete set null,
  user_id bigint references public.users (id) on update cascade on delete set null,
  status text default 'Created',
  tx_hash text,
  fortis_request_id text,
  buyer_wallet_address text,
  seller_wallet_address text,
  token_mint_address text,
  nonce text,
  error_message text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists users_email_key on public.users (email);
create unique index if not exists users_solana_wallet_address_key
  on public.users (solana_wallet_address)
  where solana_wallet_address is not null;
create unique index if not exists users_auth_user_id_key
  on public.users (auth_user_id)
  where auth_user_id is not null;

create unique index if not exists listings_token_mint_address_key
  on public.listings (token_mint_address)
  where token_mint_address is not null;

create unique index if not exists orders_nonce_key
  on public.orders (nonce)
  where nonce is not null;
create unique index if not exists orders_fortis_request_id_key
  on public.orders (fortis_request_id)
  where fortis_request_id is not null;

create index if not exists listings_owner_id_idx on public.listings (owner_id);
create index if not exists listings_tokenization_status_idx on public.listings (tokenization_status);
create index if not exists orders_listing_id_idx on public.orders (listing_id);
create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_status_idx on public.orders (status);

commit;
