begin;

alter table if exists public.users
  add column if not exists auth_user_id uuid,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

alter table if exists public.listings
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

alter table if exists public.orders
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.users
set updated_at = timezone('utc', now())
where updated_at is null;

update public.listings
set
  images = coalesce(images, '{}'::text[]),
  tokenization_status = coalesce(tokenization_status, 'draft'),
  updated_at = timezone('utc', now())
where images is null
   or tokenization_status is null
   or updated_at is null;

update public.orders
set
  status = case
    when status is null then 'Created'
    when lower(status) = 'completed' then 'Success'
    else status
  end,
  updated_at = timezone('utc', now())
where status is null
   or lower(status) = 'completed'
   or updated_at is null;

alter table public.listings
  alter column images set default '{}'::text[],
  alter column tokenization_status set default 'draft';

alter table public.orders
  alter column status set default 'Created';

alter table public.listings
  alter column price_fiat type numeric(18, 2)
  using case
    when price_fiat is null then null
    else round(price_fiat::numeric, 2)
  end;

alter table public.listings
  alter column price_crypto type numeric(38, 9)
  using case
    when price_crypto is null then null
    else round(price_crypto::numeric, 9)
  end;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['users', 'listings', 'orders']
  loop
    begin
      execute format(
        'alter table public.%I alter column id add generated by default as identity',
        table_name
      );
    exception
      when duplicate_object or object_not_in_prerequisite_state then null;
    end;

    execute format(
      $$select setval(
        pg_get_serial_sequence('public.%I', 'id'),
        coalesce((select max(id) from public.%I), 0) + 1,
        false
      )$$,
      table_name,
      table_name
    );
  end loop;
end $$;

update public.users as users_table
set
  auth_user_id = auth_users.id,
  email = lower(coalesce(auth_users.email, users_table.email)),
  updated_at = timezone('utc', now())
from auth.users as auth_users
where lower(users_table.email) = lower(auth_users.email)
  and users_table.auth_user_id is distinct from auth_users.id;

create unique index if not exists users_auth_user_id_key
  on public.users (auth_user_id)
  where auth_user_id is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_auth_user_id_fkey'
  ) then
    alter table public.users
      add constraint users_auth_user_id_fkey
      foreign key (auth_user_id)
      references auth.users (id)
      on update cascade
      on delete set null;
  end if;
end $$;

alter table public.listings
  drop constraint if exists listings_tokenization_status_check;

alter table public.listings
  add constraint listings_tokenization_status_check
  check (tokenization_status in ('draft', 'tokenizing', 'active', 'failed'));

alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (status in ('Created', 'Pending', 'Processing', 'Success', 'Failed'));

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row
execute function public.set_row_updated_at();

drop trigger if exists set_listings_updated_at on public.listings;
create trigger set_listings_updated_at
before update on public.listings
for each row
execute function public.set_row_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_row_updated_at();

create or replace function public.handle_auth_user_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.users (
      auth_user_id,
      email,
      created_at,
      updated_at
    )
    values (
      new.id,
      coalesce(lower(new.email), new.id::text || '@auth.local'),
      timezone('utc', now()),
      timezone('utc', now())
    )
    on conflict (auth_user_id) do update
      set email = excluded.email,
          updated_at = timezone('utc', now());

    return new;
  end if;

  if tg_op = 'UPDATE' then
    update public.users
    set
      email = coalesce(lower(new.email), email),
      updated_at = timezone('utc', now())
    where auth_user_id = new.id;

    return new;
  end if;

  update public.users
  set
    auth_user_id = null,
    updated_at = timezone('utc', now())
  where auth_user_id = old.id;

  return old;
end;
$$;

drop trigger if exists on_auth_user_changed on auth.users;
create trigger on_auth_user_changed
after insert or update of email or delete on auth.users
for each row
execute function public.handle_auth_user_change();

alter table public.users enable row level security;
alter table public.listings enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Users can read their profile" on public.users;
create policy "Users can read their profile"
on public.users
for select
using (auth.uid() = auth_user_id);

drop policy if exists "Users can update their profile" on public.users;
create policy "Users can update their profile"
on public.users
for update
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "Public can read active listings" on public.listings;
create policy "Public can read active listings"
on public.listings
for select
using (
  tokenization_status = 'active'
  or exists (
    select 1
    from public.users
    where users.id = listings.owner_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "Owners can insert listings" on public.listings;
create policy "Owners can insert listings"
on public.listings
for insert
to authenticated
with check (
  exists (
    select 1
    from public.users
    where users.id = listings.owner_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "Owners can update listings" on public.listings;
create policy "Owners can update listings"
on public.listings
for update
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = listings.owner_id
      and users.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = listings.owner_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "Buyers can read their orders" on public.orders;
create policy "Buyers can read their orders"
on public.orders
for select
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "Buyers can insert their orders" on public.orders;
create policy "Buyers can insert their orders"
on public.orders
for insert
to authenticated
with check (
  exists (
    select 1
    from public.users
    where users.id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
);

drop policy if exists "Buyers can update their orders" on public.orders;
create policy "Buyers can update their orders"
on public.orders
for update
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = orders.user_id
      and users.auth_user_id = auth.uid()
  )
);

commit;
